version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  server:
    container_name: rails
    build:
      context: ./bg-meetups-back-end
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: bg_meetups_back_end_development
      PGPORT: 5432
      PGHOST: db
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./bg-meetups-back-end:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  client:
    container_name: react
    build:
      context: ./bg-meetups-front-end
    volumes:
      - ./bg-meetups-front-end/src:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENVIRONMENT=development
    depends_on:
      - server
